name: books_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  http:
  hive:
  hive_flutter:
  sizer:
  get:
  font_awesome_flutter:
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
